services:
  mongodb:
    image: docker.io/library/mongo:8
    container_name: openoma-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: openoma
    volumes:
      - openoma-mongo-data:/data/db

volumes:
  openoma-mongo-data:
